spring:
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 900MB
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: GMT+8
server:
  context-path: /
  port: 8089

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql