spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/diving?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    com.liaoin.diving.mapper: debug

mybatis:
  mapper-locations: classpath*:com/liaoin/diving/mapper/*Mapper.xml
  executor-type: simple
  type-aliases-package : com.liaoyin.diving.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.liaoin.diving.mapper: debug

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
<<<<<<< HEAD
  params: count=countSql
=======
  params: count=countSql


>>>>>>> 0fa5b7f454a5e7274b86cd822bf03d18c6f3f9ac
